name: Tests Runner
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache Python packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}


      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install packages
        run: |
          # Postgres dev headers for pg_config
          # libpq-dev
          # Graphviz support
          # python3-dev graphviz libgraphviz-dev
          sudo apt install \
          libpq-dev \
          python3-dev graphviz libgraphviz-dev

      - name: Install packages
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Check types
        run: make mypy

      - name: Test it
        run: make coverage
        env:
          SECRET_KEY: 'a secret to everybody'
          SECURE_SSL_REDIRECT: 'off'

      - name: Check deploy configuration
        run: ./manage.py check --deploy
        env:
          SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3knbf&q$5x16#o%1im-s7!'
